// packages/web-component/src/index.ts
/**
 * @rudra/web-component — Custom element for the Rudra Office editor.
 *
 * @example
 * ```html
 * <script type="module" src="@rudra/web-component"></script>
 * <s1-editor
 *   theme="default"
 *   toolbar="standard"
 * ></s1-editor>
 * ```
 */

import { S1Editor, Toolbars } from '@rudra/editor';
import type { Format } from '@rudra/editor';

export class S1EditorElement extends HTMLElement {
  private editor: S1Editor | null = null;
  private _shadow: ShadowRoot;

  static get observedAttributes() {
    return ['theme', 'toolbar', 'read-only', 'src'];
  }

  constructor() {
    super();
    this._shadow = this.attachShadow({ mode: 'open' });
    this._shadow.innerHTML = `
      <style>
        :host { display: block; width: 100%; height: 100%; }
        .s1-container { width: 100%; height: 100%; }
      </style>
      <div class="s1-container"></div>
    `;
  }

  async connectedCallback() {
    const container = this._shadow.querySelector('.s1-container') as HTMLElement;
    if (!container) return;

    const theme = this.getAttribute('theme') || 'default';
    const toolbarName = this.getAttribute('toolbar') || 'standard';
    const readOnly = this.hasAttribute('read-only');

    const toolbar = (Toolbars as any)[toolbarName] || Toolbars.standard;

    this.editor = await S1Editor.create(container, {
      theme: theme as any,
      toolbar,
      readOnly,
      onReady: () => this.dispatchEvent(new CustomEvent('ready')),
      onChange: (e) => this.dispatchEvent(new CustomEvent('change', { detail: e })),
    });

    // Auto-load src if set
    const src = this.getAttribute('src');
    if (src) {
      await this.editor.openUrl(src);
    }
  }

  disconnectedCallback() {
    this.editor?.destroy();
    this.editor = null;
  }

  attributeChangedCallback(name: string, _old: string, value: string) {
    if (!this.editor) return;
    if (name === 'theme') this.editor.setTheme(value);
    if (name === 'read-only') this.editor.readOnly = value !== null;
    if (name === 'toolbar') {
      const tb = (Toolbars as any)[value] || Toolbars.standard;
      this.editor.setToolbar(tb);
    }
  }

  // ─── Public API ─────────────────────────────────

  /** Open a document from bytes. */
  open(data: ArrayBuffer) { this.editor?.open(data); }

  /** Open a document from URL. */
  async openUrl(url: string) { await this.editor?.openUrl(url); }

  /** Create a new document. */
  createNew() { this.editor?.createNew(); }

  /** Export the document. */
  async exportDocument(format: Format): Promise<Blob | undefined> {
    return this.editor?.exportDocument(format);
  }
}

// Register the custom element
if (!customElements.get('s1-editor')) {
  customElements.define('s1-editor', S1EditorElement);
}

export { Toolbars } from '@rudra/editor';

// packages/react/src/index.tsx
/**
 * @rudra/react — React adapter for the Rudra Office editor.
 *
 * @example
 * ```tsx
 * import { S1EditorComponent } from '@rudra/react';
 *
 * function MyApp() {
 *   return (
 *     <S1EditorComponent
 *       theme="default"
 *       toolbar="standard"
 *       onReady={() => console.log('Ready!')}
 *       onChange={(e) => console.log('Changed:', e)}
 *     />
 *   );
 * }
 * ```
 */

import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';
import { S1Editor, Toolbars } from '@rudra/editor';
import type { EditorOptions, Format, ToolbarConfig } from '@rudra/editor';

export interface S1EditorProps extends Omit<EditorOptions, 'toolbar'> {
  /** Toolbar preset name or custom config. */
  toolbar?: keyof typeof Toolbars | ToolbarConfig | false;
  /** CSS class for the container. */
  className?: string;
  /** Inline style for the container. */
  style?: React.CSSProperties;
}

export interface S1EditorRef {
  /** The underlying S1Editor instance. */
  editor: S1Editor | null;
  /** Open a document from bytes. */
  open: (data: ArrayBuffer) => void;
  /** Open a document from URL. */
  openUrl: (url: string) => Promise<void>;
  /** Create a new document. */
  createNew: () => void;
  /** Export the document. */
  exportDocument: (format: Format) => Promise<Blob>;
}

export const S1EditorComponent = forwardRef<S1EditorRef, S1EditorProps>(
  function S1EditorComponent(props, ref) {
    const containerRef = useRef<HTMLDivElement>(null);
    const editorRef = useRef<S1Editor | null>(null);

    const {
      toolbar = 'standard',
      className,
      style,
      ...editorOptions
    } = props;

    useImperativeHandle(ref, () => ({
      get editor() { return editorRef.current; },
      open: (data: ArrayBuffer) => editorRef.current?.open(data),
      openUrl: (url: string) => editorRef.current?.openUrl(url) ?? Promise.resolve(),
      createNew: () => editorRef.current?.createNew(),
      exportDocument: (format: Format) =>
        editorRef.current?.exportDocument(format) ?? Promise.reject(new Error('Editor not ready')),
    }));

    useEffect(() => {
      if (!containerRef.current) return;

      const resolvedToolbar = toolbar === false
        ? false
        : typeof toolbar === 'string'
          ? Toolbars[toolbar]
          : toolbar;

      let mounted = true;
      let editor: S1Editor | null = null;

      S1Editor.create(containerRef.current, {
        ...editorOptions,
        toolbar: resolvedToolbar || undefined,
      }).then((e) => {
        if (!mounted) { e.destroy(); return; }
        editor = e;
        editorRef.current = e;
      });

      return () => {
        mounted = false;
        editor?.destroy();
        editorRef.current = null;
      };
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    return (
      <div
        ref={containerRef}
        className={className}
        style={{ width: '100%', height: '100%', ...style }}
      />
    );
  }
);

export { S1Editor, Toolbars } from '@rudra/editor';
export type { EditorOptions, Format, ToolbarConfig, ToolbarItem, Theme } from '@rudra/editor';
